// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCB_U95lI9i1e6s1KBNvZMhknJY-2RVmss',
    appId: '1:1046538651864:web:20c5527ea35eae9b46afad',
    messagingSenderId: '1046538651864',
    projectId: 'coloc-app-b9079',
    authDomain: 'coloc-app-b9079.firebaseapp.com',
    storageBucket: 'coloc-app-b9079.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCboluq2OznXpBDOdQwlx9inOIt4dbN1WQ',
    appId: '1:1046538651864:android:3631c891bffbc19c46afad',
    messagingSenderId: '1046538651864',
    projectId: 'coloc-app-b9079',
    storageBucket: 'coloc-app-b9079.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCTfRE4g11gvDcmFZgc9zSbord_c96tQ8Y',
    appId: '1:1046538651864:ios:5da884f070b989db46afad',
    messagingSenderId: '1046538651864',
    projectId: 'coloc-app-b9079',
    storageBucket: 'coloc-app-b9079.appspot.com',
    androidClientId: '1046538651864-89lh37te4m724kbk1s0g7q8mekrqoqk5.apps.googleusercontent.com',
    iosClientId: '1046538651864-5fbhltkva0e96prdq6f4112f1qbmku1l.apps.googleusercontent.com',
    iosBundleId: 'com.example.colocApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCTfRE4g11gvDcmFZgc9zSbord_c96tQ8Y',
    appId: '1:1046538651864:ios:5da884f070b989db46afad',
    messagingSenderId: '1046538651864',
    projectId: 'coloc-app-b9079',
    storageBucket: 'coloc-app-b9079.appspot.com',
    androidClientId: '1046538651864-89lh37te4m724kbk1s0g7q8mekrqoqk5.apps.googleusercontent.com',
    iosClientId: '1046538651864-5fbhltkva0e96prdq6f4112f1qbmku1l.apps.googleusercontent.com',
    iosBundleId: 'com.example.colocApp',
  );
}
